server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: javageoip
  datasource:
    database: geoip
    host: 172.17.33.48
    port: 30001
    driver-class-name: org.postgresql.Driver
    username: paul
    password: atreides
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: health, startup, beans, info, metrics