apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-backend
spec:
  rules:
    - http:
        paths:
        - path: /db
          pathType: Prefix
          backend:
            service: 
              name: postgresdb-service
              port:
                number: 5432
