apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoipdb.fullname" . }}
  labels:
    {{- include "geoipdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: tcp
  selector:
    {{- include "geoipdb.selectorLabels" . | nindent 4 }}
