apiVersion: v1
kind: Service
metadata:
  name: postgresdb-service
spec:
  type: NodePort        
  selector:
    app: postgresdb
  ports:
    - protocol: TCP          
      port: 5432
      targetPort: 5432
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007 