apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoipdb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.postgresql.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.postgresql.name }}
    spec:
      containers:
        - name: {{ .Values.postgresql.name }}
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: storage
              mountPath: /data/db
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config 
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: password
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: postgresdb-pvc