replicaCount: 1

image:
  repository:  luciendelachance/javageoip
  tag: 1.0.10
  pullPolicy: Always

postgresql:
  repository: luciendelachance/geoipdb
  tag: 1.0.10
  username: "paul"
  password: "atreides"  
  dbName: "geoip"
  port: 5432
  nodePort: 30002
  name: "geoipdb"
  host: "geoipdb"
  serviceName: "geoipdb-service"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "paul"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  name: javageoip-service
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
  args:
    - /nginx-ingress-controller
    - --tcp-services-configmap=ingress-nginx/db-services          
  tls: []

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
